export const allCountryCode = {
	AF: { name: "Afghanistan", flag: "🇦🇫", dial_code: "+93" },
	AX: { name: "Åland Islands", flag: "🇦🇽", dial_code: "+358" },
	AL: { name: "Albania", flag: "🇦🇱", dial_code: "+355" },
	DZ: { name: "Algeria", flag: "🇩🇿", dial_code: "+213" },
	AS: { name: "American Samoa", flag: "🇦🇸", dial_code: "+1684" },
	AD: { name: "Andorra", flag: "🇦🇩", dial_code: "+376" },
	AO: { name: "Angola", flag: "🇦🇴", dial_code: "+244" },
	AI: { name: "Anguilla", flag: "🇦🇮", dial_code: "+1264" },
	AQ: { name: "Antarctica", flag: "🇦🇶", dial_code: "+672" },
	AG: { name: "Antigua and Barbuda", flag: "🇦🇬", dial_code: "+1268" },
	AR: { name: "Argentina", flag: "🇦🇷", dial_code: "+54" },
	AM: { name: "Armenia", flag: "🇦🇲", dial_code: "+374" },
	AW: { name: "Aruba", flag: "🇦🇼", dial_code: "+297" },
	AU: { name: "Australia", flag: "🇦🇺", dial_code: "+61" },
	AT: { name: "Austria", flag: "🇦🇹", dial_code: "+43" },
	AZ: { name: "Azerbaijan", flag: "🇦🇿", dial_code: "+994" },
	BS: { name: "Bahamas", flag: "🇧🇸", dial_code: "+1242" },
	BH: { name: "Bahrain", flag: "🇧🇭", dial_code: "+973" },
	BD: { name: "Bangladesh", flag: "🇧🇩", dial_code: "+880" },
	BB: { name: "Barbados", flag: "🇧🇧", dial_code: "+1246" },
	BY: { name: "Belarus", flag: "🇧🇾", dial_code: "+375" },
	BE: { name: "Belgium", flag: "🇧🇪", dial_code: "+32" },
	BZ: { name: "Belize", flag: "🇧🇿", dial_code: "+501" },
	BJ: { name: "Benin", flag: "🇧🇯", dial_code: "+229" },
	BM: { name: "Bermuda", flag: "🇧🇲", dial_code: "+1441" },
	BT: { name: "Bhutan", flag: "🇧🇹", dial_code: "+975" },
	BO: {
		name: "Bolivia, Plurinational State of bolivia",
		flag: "🇧🇴",
		dial_code: "+591",
	},
	BA: { name: "Bosnia and Herzegovina", flag: "🇧🇦", dial_code: "+387" },
	BW: { name: "Botswana", flag: "🇧🇼", dial_code: "+267" },
	BV: { name: "Bouvet Island", flag: "🇧🇻", dial_code: "+47" },
	BR: { name: "Brazil", flag: "🇧🇷", dial_code: "+55" },
	IO: { name: "British Indian Ocean Territory", flag: "🇮🇴", dial_code: "+246" },
	BN: { name: "Brunei Darussalam", flag: "🇧🇳", dial_code: "+673" },
	BG: { name: "Bulgaria", flag: "🇧🇬", dial_code: "+359" },
	BF: { name: "Burkina Faso", flag: "🇧🇫", dial_code: "+226" },
	BI: { name: "Burundi", flag: "🇧🇮", dial_code: "+257" },
	KH: { name: "Cambodia", flag: "🇰🇭", dial_code: "+855" },
	CM: { name: "Cameroon", flag: "🇨🇲", dial_code: "+237" },
	CA: { name: "Canada", flag: "🇨🇦", dial_code: "+1" },
	CV: { name: "Cape Verde", flag: "🇨🇻", dial_code: "+238" },
	KY: { name: "Cayman Islands", flag: "🇰🇾", dial_code: "+345" },
	CF: { name: "Central African Republic", flag: "🇨🇫", dial_code: "+236" },
	TD: { name: "Chad", flag: "🇹🇩", dial_code: "+235" },
	CL: { name: "Chile", flag: "🇨🇱", dial_code: "+56" },
	CN: { name: "China", flag: "🇨🇳", dial_code: "+86" },
	CX: { name: "Christmas Island", flag: "🇨🇽", dial_code: "+61" },
	CC: { name: "Cocos (Keeling) Islands", flag: "🇨🇨", dial_code: "+61" },
	CO: { name: "Colombia", flag: "🇨🇴", dial_code: "+57" },
	KM: { name: "Comoros", flag: "🇰🇲", dial_code: "+269" },
	CG: { name: "Congo", flag: "🇨🇬", dial_code: "+242" },
	CD: {
		name: "Congo, The Democratic Republic of the Congo",
		flag: "🇨🇩",
		dial_code: "+243",
	},
	CK: { name: "Cook Islands", flag: "🇨🇰", dial_code: "+682" },
	CR: { name: "Costa Rica", flag: "🇨🇷", dial_code: "+506" },
	CI: { name: "Cote d'Ivoire", flag: "🇨🇮", dial_code: "+225" },
	HR: { name: "Croatia", flag: "🇭🇷", dial_code: "+385" },
	CU: { name: "Cuba", flag: "🇨🇺", dial_code: "+53" },
	CY: { name: "Cyprus", flag: "🇨🇾", dial_code: "+357" },
	CZ: { name: "Czech Republic", flag: "🇨🇿", dial_code: "+420" },
	DK: { name: "Denmark", flag: "🇩🇰", dial_code: "+45" },
	DJ: { name: "Djibouti", flag: "🇩🇯", dial_code: "+253" },
	DM: { name: "Dominica", flag: "🇩🇲", dial_code: "+1767" },
	DO: { name: "Dominican Republic", flag: "🇩🇴", dial_code: "+1849" },
	EC: { name: "Ecuador", flag: "🇪🇨", dial_code: "+593" },
	EG: { name: "Egypt", flag: "🇪🇬", dial_code: "+20" },
	SV: { name: "El Salvador", flag: "🇸🇻", dial_code: "+503" },
	GQ: { name: "Equatorial Guinea", flag: "🇬🇶", dial_code: "+240" },
	ER: { name: "Eritrea", flag: "🇪🇷", dial_code: "+291" },
	EE: { name: "Estonia", flag: "🇪🇪", dial_code: "+372" },
	ET: { name: "Ethiopia", flag: "🇪🇹", dial_code: "+251" },
	FK: { name: "Falkland Islands (Malvinas)", flag: "🇫🇰", dial_code: "+500" },
	FO: { name: "Faroe Islands", flag: "🇫🇴", dial_code: "+298" },
	FJ: { name: "Fiji", flag: "🇫🇯", dial_code: "+679" },
	FI: { name: "Finland", flag: "🇫🇮", dial_code: "+358" },
	FR: { name: "France", flag: "🇫🇷", dial_code: "+33" },
	GF: { name: "French Guiana", flag: "🇬🇫", dial_code: "+594" },
	PF: { name: "French Polynesia", flag: "🇵🇫", dial_code: "+689" },
	TF: { name: "French Southern Territories", flag: "🇹🇫", dial_code: "+262" },
	GA: { name: "Gabon", flag: "🇬🇦", dial_code: "+241" },
	GM: { name: "Gambia", flag: "🇬🇲", dial_code: "+220" },
	GE: { name: "Georgia", flag: "🇬🇪", dial_code: "+995" },
	DE: { name: "Germany", flag: "🇩🇪", dial_code: "+49" },
	GH: { name: "Ghana", flag: "🇬🇭", dial_code: "+233" },
	GI: { name: "Gibraltar", flag: "🇬🇮", dial_code: "+350" },
	GR: { name: "Greece", flag: "🇬🇷", dial_code: "+30" },
	GL: { name: "Greenland", flag: "🇬🇱", dial_code: "+299" },
	GD: { name: "Grenada", flag: "🇬🇩", dial_code: "+1473" },
	GP: { name: "Guadeloupe", flag: "🇬🇵", dial_code: "+590" },
	GU: { name: "Guam", flag: "🇬🇺", dial_code: "+1671" },
	GT: { name: "Guatemala", flag: "🇬🇹", dial_code: "+502" },
	GG: { name: "Guernsey", flag: "🇬🇬", dial_code: "+44" },
	GN: { name: "Guinea", flag: "🇬🇳", dial_code: "+224" },
	GW: { name: "Guinea-Bissau", flag: "🇬🇼", dial_code: "+245" },
	GY: { name: "Guyana", flag: "🇬🇾", dial_code: "+592" },
	HT: { name: "Haiti", flag: "🇭🇹", dial_code: "+509" },
	HM: {
		name: "Heard Island and Mcdonald Islands",
		flag: "🇭🇲",
		dial_code: "+672",
	},
	VA: { name: "Holy See (Vatican City State)", flag: "🇻🇦", dial_code: "+379" },
	HN: { name: "Honduras", flag: "🇭🇳", dial_code: "+504" },
	HK: { name: "Hong Kong", flag: "🇭🇰", dial_code: "+852" },
	HU: { name: "Hungary", flag: "🇭🇺", dial_code: "+36" },
	IS: { name: "Iceland", flag: "🇮🇸", dial_code: "+354" },
	IN: { name: "India", flag: "🇮🇳", dial_code: "+91" },
	ID: { name: "Indonesia", flag: "🇮🇩", dial_code: "+62" },
	IR: {
		name: "Iran, Islamic Republic of Persian Gulf",
		flag: "🇮🇷",
		dial_code: "+98",
	},
	IQ: { name: "Iraq", flag: "🇮🇶", dial_code: "+964" },
	IE: { name: "Ireland", flag: "🇮🇪", dial_code: "+353" },
	IM: { name: "Isle of Man", flag: "🇮🇲", dial_code: "+44" },
	IL: { name: "Israel", flag: "🇮🇱", dial_code: "+972" },
	IT: { name: "Italy", flag: "🇮🇹", dial_code: "+39" },
	JM: { name: "Jamaica", flag: "🇯🇲", dial_code: "+1876" },
	JP: { name: "Japan", flag: "🇯🇵", dial_code: "+81" },
	JE: { name: "Jersey", flag: "🇯🇪", dial_code: "+44" },
	JO: { name: "Jordan", flag: "🇯🇴", dial_code: "+962" },
	KZ: { name: "Kazakhstan", flag: "🇰🇿", dial_code: "+7" },
	KE: { name: "Kenya", flag: "🇰🇪", dial_code: "+254" },
	KI: { name: "Kiribati", flag: "🇰🇮", dial_code: "+686" },
	KP: {
		name: "Korea, Democratic People's Republic of Korea",
		flag: "🇰🇵",
		dial_code: "+850",
	},
	KR: { name: "Korea, Republic of South Korea", flag: "🇰🇷", dial_code: "+82" },
	XK: { name: "Kosovo", flag: "🇽🇰", dial_code: "+383" },
	KW: { name: "Kuwait", flag: "🇰🇼", dial_code: "+965" },
	KG: { name: "Kyrgyzstan", flag: "🇰🇬", dial_code: "+996" },
	LA: { name: "Laos", flag: "🇱🇦", dial_code: "+856" },
	LV: { name: "Latvia", flag: "🇱🇻", dial_code: "+371" },
	LB: { name: "Lebanon", flag: "🇱🇧", dial_code: "+961" },
	LS: { name: "Lesotho", flag: "🇱🇸", dial_code: "+266" },
	LR: { name: "Liberia", flag: "🇱🇷", dial_code: "+231" },
	LY: { name: "Libyan Arab Jamahiriya", flag: "🇱🇾", dial_code: "+218" },
	LI: { name: "Liechtenstein", flag: "🇱🇮", dial_code: "+423" },
	LT: { name: "Lithuania", flag: "🇱🇹", dial_code: "+370" },
	LU: { name: "Luxembourg", flag: "🇱🇺", dial_code: "+352" },
	MO: { name: "Macao", flag: "🇲🇴", dial_code: "+853" },
	MK: { name: "Macedonia", flag: "🇲🇰", dial_code: "+389" },
	MG: { name: "Madagascar", flag: "🇲🇬", dial_code: "+261" },
	MW: { name: "Malawi", flag: "🇲🇼", dial_code: "+265" },
	MY: { name: "Malaysia", flag: "🇲🇾", dial_code: "+60" },
	MV: { name: "Maldives", flag: "🇲🇻", dial_code: "+960" },
	ML: { name: "Mali", flag: "🇲🇱", dial_code: "+223" },
	MT: { name: "Malta", flag: "🇲🇹", dial_code: "+356" },
	MH: { name: "Marshall Islands", flag: "🇲🇭", dial_code: "+692" },
	MQ: { name: "Martinique", flag: "🇲🇶", dial_code: "+596" },
	MR: { name: "Mauritania", flag: "🇲🇷", dial_code: "+222" },
	MU: { name: "Mauritius", flag: "🇲🇺", dial_code: "+230" },
	YT: { name: "Mayotte", flag: "🇾🇹", dial_code: "+262" },
	MX: { name: "Mexico", flag: "🇲🇽", dial_code: "+52" },
	FM: {
		name: "Micronesia, Federated States of Micronesia",
		flag: "🇫🇲",
		dial_code: "+691",
	},
	MD: { name: "Moldova", flag: "🇲🇩", dial_code: "+373" },
	MC: { name: "Monaco", flag: "🇲🇨", dial_code: "+377" },
	MN: { name: "Mongolia", flag: "🇲🇳", dial_code: "+976" },
	ME: { name: "Montenegro", flag: "🇲🇪", dial_code: "+382" },
	MS: { name: "Montserrat", flag: "🇲🇸", dial_code: "+1664" },
	MA: { name: "Morocco", flag: "🇲🇦", dial_code: "+212" },
	MZ: { name: "Mozambique", flag: "🇲🇿", dial_code: "+258" },
	MM: { name: "Myanmar", flag: "🇲🇲", dial_code: "+95" },
	NA: { name: "Namibia", flag: "🇳🇦", dial_code: "+264" },
	NR: { name: "Nauru", flag: "🇳🇷", dial_code: "+674" },
	NP: { name: "Nepal", flag: "🇳🇵", dial_code: "+977" },
	NL: { name: "Netherlands", flag: "🇳🇱", dial_code: "+31" },
	AN: { name: "Netherlands Antilles", flag: "", dial_code: "+599" },
	NC: { name: "New Caledonia", flag: "🇳🇨", dial_code: "+687" },
	NZ: { name: "New Zealand", flag: "🇳🇿", dial_code: "+64" },
	NI: { name: "Nicaragua", flag: "🇳🇮", dial_code: "+505" },
	NE: { name: "Niger", flag: "🇳🇪", dial_code: "+227" },
	NG: { name: "Nigeria", flag: "🇳🇬", dial_code: "+234" },
	NU: { name: "Niue", flag: "🇳🇺", dial_code: "+683" },
	NF: { name: "Norfolk Island", flag: "🇳🇫", dial_code: "+672" },
	MP: { name: "Northern Mariana Islands", flag: "🇲🇵", dial_code: "+1670" },
	NO: { name: "Norway", flag: "🇳🇴", dial_code: "+47" },
	OM: { name: "Oman", flag: "🇴🇲", dial_code: "+968" },
	PK: { name: "Pakistan", flag: "🇵🇰", dial_code: "+92" },
	PW: { name: "Palau", flag: "🇵🇼", dial_code: "+680" },
	PS: {
		name: "Palestinian Territory, Occupied",
		flag: "🇵🇸",
		dial_code: "+970",
	},
	PA: { name: "Panama", flag: "🇵🇦", dial_code: "+507" },
	PG: { name: "Papua New Guinea", flag: "🇵🇬", dial_code: "+675" },
	PY: { name: "Paraguay", flag: "🇵🇾", dial_code: "+595" },
	PE: { name: "Peru", flag: "🇵🇪", dial_code: "+51" },
	PH: { name: "Philippines", flag: "🇵🇭", dial_code: "+63" },
	PN: { name: "Pitcairn", flag: "🇵🇳", dial_code: "+64" },
	PL: { name: "Poland", flag: "🇵🇱", dial_code: "+48" },
	PT: { name: "Portugal", flag: "🇵🇹", dial_code: "+351" },
	PR: { name: "Puerto Rico", flag: "🇵🇷", dial_code: "+1939" },
	QA: { name: "Qatar", flag: "🇶🇦", dial_code: "+974" },
	RO: { name: "Romania", flag: "🇷🇴", dial_code: "+40" },
	RU: { name: "Russia", flag: "🇷🇺", dial_code: "+7" },
	RW: { name: "Rwanda", flag: "🇷🇼", dial_code: "+250" },
	RE: { name: "Reunion", flag: "🇷🇪", dial_code: "+262" },
	BL: { name: "Saint Barthelemy", flag: "🇧🇱", dial_code: "+590" },
	SH: {
		name: "Saint Helena, Ascension and Tristan Da Cunha",
		flag: "🇸🇭",
		dial_code: "+290",
	},
	KN: { name: "Saint Kitts and Nevis", flag: "🇰🇳", dial_code: "+1869" },
	LC: { name: "Saint Lucia", flag: "🇱🇨", dial_code: "+1758" },
	MF: { name: "Saint Martin", flag: "🇲🇫", dial_code: "+590" },
	PM: { name: "Saint Pierre and Miquelon", flag: "🇵🇲", dial_code: "+508" },
	VC: {
		name: "Saint Vincent and the Grenadines",
		flag: "🇻🇨",
		dial_code: "+1784",
	},
	WS: { name: "Samoa", flag: "🇼🇸", dial_code: "+685" },
	SM: { name: "San Marino", flag: "🇸🇲", dial_code: "+378" },
	ST: { name: "Sao Tome and Principe", flag: "🇸🇹", dial_code: "+239" },
	SA: { name: "Saudi Arabia", flag: "🇸🇦", dial_code: "+966" },
	SN: { name: "Senegal", flag: "🇸🇳", dial_code: "+221" },
	RS: { name: "Serbia", flag: "🇷🇸", dial_code: "+381" },
	SC: { name: "Seychelles", flag: "🇸🇨", dial_code: "+248" },
	SL: { name: "Sierra Leone", flag: "🇸🇱", dial_code: "+232" },
	SG: { name: "Singapore", flag: "🇸🇬", dial_code: "+65" },
	SK: { name: "Slovakia", flag: "🇸🇰", dial_code: "+421" },
	SI: { name: "Slovenia", flag: "🇸🇮", dial_code: "+386" },
	SB: { name: "Solomon Islands", flag: "🇸🇧", dial_code: "+677" },
	SO: { name: "Somalia", flag: "🇸🇴", dial_code: "+252" },
	ZA: { name: "South Africa", flag: "🇿🇦", dial_code: "+27" },
	SS: { name: "South Sudan", flag: "🇸🇸", dial_code: "+211" },
	GS: {
		name: "South Georgia and the South Sandwich Islands",
		flag: "🇬🇸",
		dial_code: "+500",
	},
	ES: { name: "Spain", flag: "🇪🇸", dial_code: "+34" },
	LK: { name: "Sri Lanka", flag: "🇱🇰", dial_code: "+94" },
	SD: { name: "Sudan", flag: "🇸🇩", dial_code: "+249" },
	SR: { name: "Suriname", flag: "🇸🇷", dial_code: "+597" },
	SJ: { name: "Svalbard and Jan Mayen", flag: "🇸🇯", dial_code: "+47" },
	SZ: { name: "Eswatini", flag: "🇸🇿", dial_code: "+268" },
	SE: { name: "Sweden", flag: "🇸🇪", dial_code: "+46" },
	CH: { name: "Switzerland", flag: "🇨🇭", dial_code: "+41" },
	SY: { name: "Syrian Arab Republic", flag: "🇸🇾", dial_code: "+963" },
	TW: { name: "Taiwan", flag: "🇹🇼", dial_code: "+886" },
	TJ: { name: "Tajikistan", flag: "🇹🇯", dial_code: "+992" },
	TZ: {
		name: "Tanzania, United Republic of Tanzania",
		flag: "🇹🇿",
		dial_code: "+255",
	},
	TH: { name: "Thailand", flag: "🇹🇭", dial_code: "+66" },
	TL: { name: "Timor-Leste", flag: "🇹🇱", dial_code: "+670" },
	TG: { name: "Togo", flag: "🇹🇬", dial_code: "+228" },
	TK: { name: "Tokelau", flag: "🇹🇰", dial_code: "+690" },
	TO: { name: "Tonga", flag: "🇹🇴", dial_code: "+676" },
	TT: { name: "Trinidad and Tobago", flag: "🇹🇹", dial_code: "+1868" },
	TN: { name: "Tunisia", flag: "🇹🇳", dial_code: "+216" },
	TR: { name: "Turkey", flag: "🇹🇷", dial_code: "+90" },
	TM: { name: "Turkmenistan", flag: "🇹🇲", dial_code: "+993" },
	TC: { name: "Turks and Caicos Islands", flag: "🇹🇨", dial_code: "+1649" },
	TV: { name: "Tuvalu", flag: "🇹🇻", dial_code: "+688" },
	UG: { name: "Uganda", flag: "🇺🇬", dial_code: "+256" },
	UA: { name: "Ukraine", flag: "🇺🇦", dial_code: "+380" },
	AE: { name: "United Arab Emirates", flag: "🇦🇪", dial_code: "+971" },
	GB: { name: "United Kingdom", flag: "🇬🇧", dial_code: "+44" },
	US: { name: "United States", flag: "🇺🇸", dial_code: "+1" },
	UY: { name: "Uruguay", flag: "🇺🇾", dial_code: "+598" },
	UZ: { name: "Uzbekistan", flag: "🇺🇿", dial_code: "+998" },
	VU: { name: "Vanuatu", flag: "🇻🇺", dial_code: "+678" },
	VE: {
		name: "Venezuela, Bolivarian Republic of Venezuela",
		flag: "🇻🇪",
		dial_code: "+58",
	},
	VN: { name: "Vietnam", flag: "🇻🇳", dial_code: "+84" },
	VG: { name: "Virgin Islands, British", flag: "🇻🇬", dial_code: "+1284" },
	VI: { name: "Virgin Islands, U.S.", flag: "🇻🇮", dial_code: "+1340" },
	WF: { name: "Wallis and Futuna", flag: "🇼🇫", dial_code: "+681" },
	YE: { name: "Yemen", flag: "🇾🇪", dial_code: "+967" },
	ZM: { name: "Zambia", flag: "🇿🇲", dial_code: "+260" },
	ZW: { name: "Zimbabwe", flag: "🇿🇼", dial_code: "+263" },
};
